[Log-in Flow] Create new Verify Code Screen
calblueprint/alemany pull request #40
Opened 2021-11-11 06:26 UTC by nikkisuzani

## Summary
Added a verify code screen so it comes after the "enter phone number" screen.
## Test Plan
- plan to review
## Other
### Next Steps
Fix the verification code so you can click on more than one place, fix it so it doesn't bug out if you click cancel during the Recatpcha, figure out whether or not to include props, style.
### Relevant Links
### Online Sources
### Related PRs
## Screenshots and Tests

https://user-images.githubusercontent.com/66634057/141248596-da5b836e-1f0b-4aa3-82a4-bfe87bf46514.MP4

CC: @mylesdomingo

2021-11-11 17:34 UTC, kennethlien requested changes

2021-11-11 17:34 UTC, kennethlien commented on src/screens/LoginScreen.tsx
> +            const RealverificationId = await phoneProvider.verifyPhoneNumber(
Use camelCase with lowercase first letter.

2021-11-11 17:34 UTC, kennethlien commented on src/screens/LoginScreen.tsx
> +            const RealverificationId = await phoneProvider.verifyPhoneNumber(
nit: real isn't a very descriptive, see if you can use something else

2021-11-11 17:34 UTC, kennethlien commented on src/screens/VerificationScreen.tsx
> +      ) : undefined}
Instead of a ternary with undefined, use {message && /* content */}

2021-11-16 01:38 UTC, mylesdomingo approved these changes

2021-11-16 01:47 UTC, kennethlien approved these changes

2021-11-16 01:48 UTC, merged