Add ability to archive/unarchive a tree
calblueprint/alemany pull request #49
Opened 2021-11-23 05:44 UTC by kennethlien

## Summary
Add in an `active` tag to trees to represent archived/unarchived trees. Enable searching only active trees/all trees. Add toggle to archive/unarchive a tree in edit screen.
## Test Plan
Test buttons and make sure they sync up with database records. Automate testing.
## Other
Known issue, the button to switch between archived and unarchived trees can suffer from a desync? It doesn't match what is actually displayed.

## Screenshots and Tests
- if your feature is visual, attach before/after screenshots and ensure that tests still pass
CC: @mylesdomingo

2021-11-23 05:47 UTC, kennethlien commented
![image](https://user-images.githubusercontent.com/57934617/142976558-faa965c5-0dd4-47aa-b3bb-eb7810a93fad.png)![image](https://user-images.githubusercontent.com/57934617/142976565-9b48d4d1-37a4-4d55-a009-c416e9e3ad4a.png)![image](https://user-images.githubusercontent.com/57934617/142976571-97512d92-9785-4941-87d7-c512e74a1b95.png)![image](https://user-images.githubusercontent.com/57934617/142976583-852d85b5-4e0a-485b-874f-caf410788f34.png)

2021-11-25 06:07 UTC, mylesdomingo requested changes

2021-11-25 06:07 UTC, mylesdomingo commented on src/screens/LoginScreen.tsx
> +      <Button title="BYPASS" onPress={() => navigation.navigate('Root')} />
just set attemptInvisibleVerification to true, i think

https://docs.expo.dev/versions/latest/sdk/firebase-recaptcha/

also if you do this, do it as a separate PR please

2021-11-25 06:07 UTC, mylesdomingo commented on src/screens/SearchScreen.tsx
>      .filter(
we're already filtering client side here to match search queries, do we need another read operation using a .where clause? we can do the same checking if its active or not

2021-11-25 06:07 UTC, mylesdomingo commented on src/screens/SearchScreen.tsx
> +            setActive(!active);
you need to run refreshTrees in a useEffect, setActive is an async function and will not complete by the time you refresh

2021-12-02 07:35 UTC, wangannie approved these changes
Commented on some quick fixes but good to merge once those are addressed!

2021-12-02 07:35 UTC, wangannie commented on src/database/firebase.tsx
> + * getActiveTrees
nit: add details for consistency

2021-12-02 07:35 UTC, wangannie commented on src/screens/TreeDetailsScreen.tsx
> +      <Button
Very confusing that this is a button & clickable when not in edit mode -- i was clicking on it expecting it to save to firebase. Ik this is all temporary but for the sake of bug bash, change to regular text like Status: Active

2021-12-02 07:35 UTC, wangannie commented on src/screens/SearchScreen.tsx
> +        <Title>Hello</Title>
Is this here by mistake?

2022-03-12 20:12 UTC, closed without merging