Basic Containers and Pill
calblueprint/alemany pull request #57
Opened 2021-11-30 05:45 UTC by kennethlien

Row, background container, and `Pill` components for usage throughout app.

2021-11-30 05:45 UTC, kennethlien commented
![image](https://user-images.githubusercontent.com/57934617/143992436-d64549dd-60a7-44c6-9d11-756d714f0903.png)

2021-12-01 18:41 UTC, mylesdomingo requested changes

2021-12-01 18:41 UTC, mylesdomingo commented on src/components/Components.tsx
> +  return <View {...props} style={[styles.screen, props.style]} />;
what is this used for?

2021-12-01 18:41 UTC, mylesdomingo commented on src/components/Components.tsx
> +export function RowContainer(props: React.ComponentProps<typeof View>) {
im fine with creating layout components for rows and columns,  but put it in the shared components folder as `Row.tsx`

2021-12-01 18:41 UTC, mylesdomingo commented on src/components/Components.tsx
> +        <FontAwesome
Use he default text component

2022-01-27 01:22 UTC, nikkisuzani reviewed
lgtm

2022-02-09 07:37 UTC, closed without merging