[List View] Show Results Counter
calblueprint/alemany pull request #70
Opened 2022-03-07 01:02 UTC by akshaynthakur

## Summary
This PR adds a counter on the search screen that displays the number of results based on the current search as "X result(s)".

## Test Plan
To test, go to the search screen and try different search values to see the counter in action. 

## Notes
Lines 6-9: outdated import not being used anymore, was causing issues. Was unsure about deletion, so just commented out.

Syntax issue on Line 76-79: had to disable prettier because it doesn't allow {' '} as a valid way to add a space to the text, but a one-line solution doesn't work either under jsx style guidelines.  

### Next Steps
May need to adjust `marginTop` or add `marginBottom` as more components are added to the search screen.

### Relevant Links

### Online Sources

### Related PRs

## Screenshots and Tests

https://user-images.githubusercontent.com/78326649/156950559-9f406a52-8ecc-49f6-bcfc-0db43f5d557b.mp4

2022-03-07 01:35 UTC, daniellenwong approved these changes
This looks good!

2022-03-07 01:57 UTC, jjiang17 requested changes
other than the minor prettier issue everything looks good to me! good work 😃😃😃👍🏽👍🏽👍🏽👍🏽👍🏽👍🏽

2022-03-07 01:57 UTC, jjiang17 commented on src/screens/SearchScreen.js
> +// import {
you'll want to delete commented-out code

2022-03-07 01:57 UTC, jjiang17 commented on src/screens/SearchScreen.js
> +          {/* eslint-disable-next-line prettier/prettier */}
try using f-string concatenation to fix this formatting issue!

2022-03-10 02:24 UTC, jjiang17 approved these changes

2022-03-12 20:24 UTC, merged